import google.generativeai as genai
from .base import LLMProvider
from ..utils import extract_yaml_from_string

class GeminiProvider(LLMProvider):
    def generate(self, prompt: str, options: dict) -> dict:
        api_key = options.get("gemini_api_key")
        model_name = options.get("gemini_model", "gemini-1.5-flash")
        if not api_key:
            raise ValueError("Gemini API key not configured.")

        genai.configure(api_key=api_key)
        print(f"[INFO] Calling Gemini with model {model_name}")
        model = genai.GenerativeModel(model_name)
        
        response = model.generate_content(prompt)
        print(f"[TRACE] Raw response from Gemini:\n---\n{response.text}\n---")
        
        # Use the new YAML extraction function
        yaml_string = extract_yaml_from_string(response.text)
        
        # Return a dictionary compatible with the frontend
        return {
            "automation_yaml": yaml_string,
            "explanation": "Generated by Gemini." # We can improve this later
        }