import requests
from .base import LLMProvider
from ..utils import extract_yaml_from_string

class OllamaProvider(LLMProvider):
    def generate(self, prompt: str, options: dict) -> dict:
        ollama_url = options.get("ollama_url")
        model_name = options.get("ollama_model")
        if not all([ollama_url, model_name]):
            raise ValueError("Ollama URL or model not configured.")

        print(f"[INFO] Calling Ollama at {ollama_url} with model {model_name}")
        
        try:
            response = requests.post(
                f"{ollama_url}/api/generate",
                json={"model": model_name, "prompt": prompt, "stream": False},
                timeout=120,
            )
            response.raise_for_status()
            full_response_text = response.json().get("response", "")
            print(f"[TRACE] Raw response from Ollama:\n---\n{full_response_text}\n---")

            # Use the new YAML extraction function
            yaml_string = extract_yaml_from_string(full_response_text)
            
            # Return a dictionary compatible with the frontend
            return {
                "automation_yaml": yaml_string,
                "explanation": "Generated by Ollama." # We can improve this later
            }
        except requests.RequestException as e:
            raise ConnectionError(f"Could not connect to Ollama: {e}")